### PR TITLE
Support Taiwan market.

### PR DESCRIPTION
**Pull request by yccheok**
支援台湾市场。
谢谢。

### CODE REVIEW

**Comment by huanghaibin-dev** [comment]
稍等，新版本很多新功能，也支持台湾市场了，正在发布中

**Comment by huanghaibin-dev** [comment]
done

**Comment by yccheok** [comment]
嗨。看了最新改动 https://github.com/huanghaibin-dev/CalendarView/blob/master/calendarview/src/main/res/values-zh-rTW/strings.xml ， 有以下的意见。

1. 有些词汇没翻译到繁体中文，如“惊蛰”
2. 台湾地区庆祝的节日如“教師節”，是在09月28日
3. 台湾地区有些节日不庆祝，如“建黨節”。

望能修正。谢谢。

**Comment by huanghaibin-dev** [comment]
好的，谢谢支持，我参考一下发自我的iPhone------------------ Original ------------------From: Yan Cheng Cheok  <notifications@github.com>Date: Fri,Sep 14,2018 9:14 PMTo: huanghaibin-dev/CalendarView <CalendarView@noreply.github.com>Cc: 黄海彬 <huanghaibin_dev@163.com>, State change <state_change@noreply.github.com>Subject: Re: [huanghaibin-dev/CalendarView] Support Taiwan market. (#231)嗨。看了最新改动 https://github.com/huanghaibin-dev/CalendarView/blob/master/calendarview/src/main/res/values-zh-rTW/strings.xml ， 有以下的意见。

有些词汇没翻译到繁体中文，如“惊蛰”
台湾地区庆祝的节日如“教師節”，是在09月28日
台湾地区有些节日不庆祝，如“建黨節”。

望能修正。谢谢。

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/huanghaibin-dev/CalendarView","title":"huanghaibin-dev/CalendarView","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/huanghaibin-dev/CalendarView"}},"updates":{"snippets":[{"icon":"PERSON","message":"@yccheok in #231: 嗨。看了最新改动 https://github.com/huanghaibin-dev/CalendarView/blob/master/calendarview/src/main/res/values-zh-rTW/strings.xml ， 有以下的意见。\r\n\r\n1. 有些词汇没翻译到繁体中文，如“惊蛰”\r\n2. 台湾地区庆祝的节日如“教師節”，是在09月28日\r\n3. 台湾地区有些节日不庆祝，如“建黨節”。\r\n\r\n望能修正。谢谢。"}],"action":{"name":"View Pull Request","url":"https://github.com/huanghaibin-dev/CalendarView/pull/231#issuecomment-421354318"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/huanghaibin-dev/CalendarView/pull/231#issuecomment-421354318",
"url": "https://github.com/huanghaibin-dev/CalendarView/pull/231#issuecomment-421354318",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [huanghaibin-dev/CalendarView] Support Taiwan market. (#231)",
"sections": [
{
"text": "",
"activityTitle": "**Yan Cheng Cheok**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@yccheok",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"huanghaibin-dev/CalendarView\",\n\"issueId\": 231,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/huanghaibin-dev/CalendarView/pull/231#issuecomment-421354318"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 379792712\n}"
}
],
"themeColor": "26292E"
}
]

**Pull request closed without merging**
